name: CaptureTheFlag
version: ${project.version}
main: de.fel1x.capturetheflag.CaptureTheFlag
api-version: 1.16
depend: [ CrimxAPI ]
authors: [ fel1x ]
description: A CTF minigame
website: teamcrimx.de

commands:
  setup:
    description: setup
  start:
    description: start
  stats:
    description: check your stats
