name: CrimxAPI
version: ${project.version}
main: de.fel1x.teamcrimx.crimxapi.support.CrimxSpigotAPI
authors: [fel1x]
description: An API to connect our minigames with other stuff
website: teamcrimx.de

commands:
  joinme:
    description: Brodcast a joinme
  coins:
    description: Get and manage your coins
