name: CrimxAPI
version: ${project.version}
main: de.fel1x.teamcrimx.crimxapi.support.CrimxSpigotAPI
authors: [ fel1x ]
description: An API to connect our minigames with other stuff
website: teamcrimx.de
api-version: 1.16
depend:
  - ProtocolLib
  - PlayerParticles

commands:
  joinme:
    description: Brodcast a joinme
  coins:
    description: Get and manage your coins
  clan:
    description: Create a clan
  friend:
    description: Add some friends
  party:
    description: not yet

